language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11

# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coveralls

# command to run tests
script:
  - coverage run --source='.' --omit='demo.py,*wsgi.py' manage.py test activflow.tests

after_success:
  - coveralls
